
POST http://localhost:3000/users/register
content-type: application/json

{
  "name": "Edsger W. Dijkstra",
  "email": "ro@xrem.net",
  "luckyNumber": 7,
  "password": "abdef"
}

####


POST http://localhost:3000/users/login
content-type: application/json

{
  "email": "ro@xrem.net",
  "password": "abdef"
}


####

POST http://localhost:3000/users/search
content-type: application/json
x-authorization: foooo

{
    "query": "xrem"
}


####

POST http://localhost:3000/users/search
content-type: application/json
x-authorization: 4c617d2b-33a3-495e-959e-db10ff3eb130

{
    "query": "x"
}

####

PUT http://localhost:3000/users/logout
x-authorization: 4c617d2b-33a3-495e-959e-db10ff3eb130



#### 


PUT http://localhost:3000/users/logout
x-authorization: cafebabe


