
POST http://localhost:3000/users/register
content-type: application/json

{
  "name": "Edsger W. Dijkstra",
  "email": "ro@xrem.net",
  "luckyNumber": 7,
  "password": "abdef"
}

####


POST http://localhost:3000/users/login
content-type: application/json

{
  "email": "ro@xrem.net",
  "password": "abd"
}


####

POST http://localhost:3000/users/search
content-type: application/json
x-authorization: foooo

{
    "query": "xrem"
}


####

POST http://localhost:3000/users/search
content-type: application/json
x-authorization: e2f733a1-ec0b-47ff-be1b-d109551c93b4

{
    "query": "x"
}

####

PUT http://localhost:3000/users/logout
x-authorization: e2f733a1-ec0b-47ff-be1b-d109551c93b4



#### 


PUT http://localhost:3000/users/logout
x-authorization: cafebabe


